In [ ]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers.experimental import preprocessing
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [ ]:
# Load the data into a DataFrame
data = pd.read_csv('/content/modified_datas.csv')
data.head()

id   ket_waktu nama_marketplace       jenis_barang  status_promosi  \
0   1  2013-01-01           Lazada           Otomotif               0   
1   2  2013-01-01           Lazada  Perlengkapan Bayi               0   
2   3  2013-01-01           Lazada  Produk Kecantikan               0   
3   4  2013-01-01           Lazada            Minuman               0   
4   5  2013-01-01           Lazada     Buku dan Novel               0   

   total_penjualan  
0       809.148243  
1       647.504899  
2       312.767869  
3       946.490214  
4       936.897775

In [ ]:
# Convert categorical columns to string type
data['ket_waktu'] = pd.to_datetime(data['ket_waktu']).dt.strftime('%Y-%m-%d')
data['nama_marketplace'] = data['nama_marketplace'].astype(str)
data['jenis_barang'] = data['jenis_barang'].astype(str)

In [ ]:
# Encode categorical columns using label encoding
label_encoder = LabelEncoder()
data['ket_waktu'] = label_encoder.fit_transform(data['ket_waktu'])
data['nama_marketplace'] = label_encoder.fit_transform(data['nama_marketplace'])
data['jenis_barang'] = label_encoder.fit_transform(data['jenis_barang'])

In [ ]:
# Select relevant features for clustering
features = ['ket_waktu', 'nama_marketplace', 'jenis_barang', 'status_promosi', 'total_penjualan']
X = data[features].values

# Convert feature values to float32
X = X.astype('float32')

# Normalize the feature values
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [ ]:
# Create a TensorFlow K-means model
kmeans = tf.compat.v1.estimator.experimental.KMeans(num_clusters=5)

# Define an input function
input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(X, None, shuffle=True)

# Train the model
kmeans.train(input_fn=input_fn, steps=100)

In [ ]:
# Get the cluster centers
cluster_centers = kmeans.cluster_centers()

# Print cluster centers
print("Cluster Centers:")
print(cluster_centers)


Cluster Centers:
[[0.         0.         0.305462   0.         0.82406265]
 [0.         0.         0.83563    0.         0.691297  ]
 [0.         0.         0.45724028 0.         0.47342813]
 [0.         0.         0.17456588 0.         0.24816807]
 [0.         0.         0.7685885  0.         0.1857861 ]]
